before:
  hooks:
    - go mod tidy
builds:
  - binary: versionhelper
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X github.com/krafton-hq/version-helper/pkg/consts.version=v{{.Version}}

archives:
  - format: tar.gz
    name_template: |-
      versionhelper_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
