// CAUTION! DO NOT EDIT THIS FILE MANUALLY.
// This file is automatically generated from VersionHelper.exe for versioning automation.
// Author : erion@pubg.net, 2018.07~

#ifndef __FORCE_INCLUDE_VERSION_H__
    #error "Do not include this file for getting version."
#endif

#define __VER_TEXT_2(x) TEXT(x)
#define __VER_TEXT(x) __VER_TEXT_2(x)
#define __VER_TOSTR_2(x) __VER_TEXT(#x)
#define __VER_TOSTR(x) __VER_TOSTR_2(x)

#define VERSION_COLUMN_0 {{ .Major }}
#define VERSION_COLUMN_1 {{ .Minor }}
#define VERSION_COLUMN_2 {{ .Patch }}
#define VERSION_COLUMN_3 {{ .Git.Branch }}
#define VERSION_COLUMN_4 {{ .Revision }}
#define VERSION_COLUMN_6 {{ .Git.Commit }}

#define VERSION_STRING __VER_TOSTR(VERSION_COLUMN_0) __VER_TOSTR(VERSION_COLUMN_1) __VER_TOSTR(VERSION_COLUMN_2) __VER_TOSTR(VERSION_COLUMN_3) __VER_TOSTR(VERSION_COLUMN_4) __VER_TOSTR(VERSION_COLUMN_5) __VER_TEXT(".")

